SELECT *
FROM JOB;

SELECT JOB_NAME
FROM JOB;

SELECT *
FROM department;

SELECT EMP_NAME,EMAIL,PHONE,HIRE_DATE
FROM employee;

SELECT HIRE_DATE, EMP_NAME,SALARY
FROM employee;

SELECT EMP_NAME,SALARY*12 ,(SALARY +SALARY*BONUS)*12,((SALARY +SALARY*BONUS)*12)-(SALARY*0.07)
FROM employee;

SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM employee
WHERE sal_level ='S1';


SELECT EMP_NAME,SALARY,((SALARY +SALARY*NVL(BONUS , '0'))*12)-(SALARY*0.07)AS "실수령액",HIRE_DATE
FROM employee
WHERE ((SALARY +SALARY*NVL(BONUS , '0'))*12)-(SALARY*0.07) >= 50000000;


SELECT *
FROM employee
WHERE SALARY >=4000000 AND JOB_CODE ='J2';

SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM employee
WHERE DEPT_CODE IN ('D9','D5') AND HIRE_DATE < '02/1/1';

SELECT *
FROM employee
WHERE hire_date >= '90/01/01' AND  hire_date <= '01/01/01';

SELECT EMP_NAME
FROM employee
WHERE EMP_NAME LIKE '%연';

SELECT EMP_NAME, PHONE
FROM employee
WHERE NOT PHONE LIKE '010%';

SELECT *
FROM employee
WHERE (DEPT_CODE = 'D6' OR DEPT_CODE = 'D9' )AND email LIKE '____$_%' ESCAPE'$' AND
hire_date >= '90/01/01' AND  hire_date <= '00/12/01' AND SALARY >= 2700000;

SELECT EMP_NAME, SUBSTR(EMP_NO, 1, 2)AS "생년",SUBSTR(EMP_NO, 3, 2)AS "생월",SUBSTR(EMP_NO, 5, 2)AS "생일"
FROM employee;

SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO,1,8),14,'*')
FROM employee;

SELECT EMP_NAME, ABS(TRUNC(HIRE_DATE - SYSDATE)) AS "근무일수1", TRUNC(SYSDATE -HIRE_DATE )AS "근무일수2"
FROM employee;

SELECT *
FROM employee
WHERE MOD(EMP_ID,2) = 1;

SELECT *
FROM employee
WHERE hire_date <= SYSDATE - INTERVAL '20' YEAR;

SELECT EMP_NAME,TO_CHAR(SALARY,'L999,999,999') 
FROM employee;

SELECT EMP_NAME, DEPT_CODE,TO_DATE(SUBSTR(EMP_NO,1,6),'YY/MM/DD')AS"생년월일", ABS(TRUNC(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(EMP_NO,1,6), 'YYMMDD'))/12))AS "만나이"
FROM employee;

SELECT EMP_NAME, 
    DECODE(DEPT_CODE,'D5','총무부','D6','기획부','D9','영업부')
FROM employee
ORDER BY 2;

SELECT EMP_NAME, SUBSTR(EMP_NO,1,6), SUBSTR(EMP_NO,8,7),SUBSTR(EMP_NO,1,6)+ SUBSTR(EMP_NO,8,7)AS "이걸 왜.. 합치죠?"
FROM employee
WHERE EMP_ID = '201';

SELECT EMP_NAME,(SALARY + SALARY * NVL(BONUS,0))*12 AS "총연봉"
FROM employee
WHERE DEPT_CODE = 'D5';


SELECT TO_CHAR(HIRE_DATE, 'YYYY')||'년' AS "입사년도", COUNT(*)||'명' AS count
FROM employee
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY');

SELECT COUNT(*) AS "전체 직원 수",
        COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE)= 2001 THEN 1 END) AS "2001년" ,
         COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE)= 2002 THEN 1 END) AS "2002년" ,
          COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE)= 2003 THEN 1 END) AS "2003년" ,
           COUNT(CASE WHEN EXTRACT(YEAR FROM HIRE_DATE)= 2004 THEN 1 END) AS "2004년"
FROM employee

