SELECT DEPARTMENT_NAME AS "학과 명", category AS "계열"
FROM tb_department;

SELECT DEPARTMENT_NAME || '의 정원은 '||capacity ||'명 입니다.' AS "학과별 정원"
FROM tb_department;

SELECT DEPARTMENT_NAME, department_no
FROM tb_department
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT STUDENT_NAME 
FROM tb_student
WHERE ABSENCE_YN = 'Y' AND department_no = 001 
AND SUBSTR(student_ssn,8,1)=2;

SELECT STUDENT_NAME 
FROM tb_student
WHERE STUDENT_NO IN('A513079','A513090', 'A513091', 'A513110', 'A513119');

SELECT DEPARTMENT_NAME AS "학과 명", category AS "계열"
FROM tb_department
WHERE capacity >= 20 AND capacity <=30;

SELECT PROFESSOR_NAME
FROM tb_professor
WHERE DEPARTMENT_NO IS NULL;

SELECT STUDENT_NAME 
FROM tb_student
WHERE DEPARTMENT_NO IS NULL;

SELECT PREATTENDING_CLASS_NO
FROM tb_class
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

SELECT DISTINCT(CATEGORY)
FROM tb_department;

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM tb_student
WHERE ABSENCE_YN = 'N' AND SUBSTR(STUDENT_ADDRESS,1,2) IN ('전주')
AND SUBSTR( ENTRANCE_DATE,1,2)='02';


SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD')AS 입학년도
FROM tb_student;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM tb_professor
WHERE NOT professor_name LIKE '___';

SELECT PROFESSOR_NAME AS 교수이름, ABS(FLOOR(MONTHS_BETWEEN(TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RR/MM/DD'), SYSDATE)/12)+1) AS 나이
FROM tb_professor
WHERE SUBSTR(PROFESSOR_SSN,8,1)IN('1','3');

SELECT SUBSTR(PROFESSOR_NAME,2,6) AS 이름
FROM tb_professor;

SELECT STUDENT_NO, STUDENT_NAME , MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RR/MM/DD')  )/12
FROM tb_student
--WHERE          MONTHS_BETWEEN(TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RR/MM/DD'),  ENTRANCE_DATE)