SELECT *
FROM JOB;

SELECT JOB_NAME
FROM JOB;

SELECT *
FROM department;

SELECT EMP_NAME,EMAIL,PHONE,HIRE_DATE
FROM employee;

SELECT HIRE_DATE, EMP_NAME,SALARY
FROM employee;

SELECT EMP_NAME,SALARY*12 ,(SALARY +SALARY*BONUS)*12,((SALARY +SALARY*BONUS)*12)-(SALARY*0.07)
FROM employee;

SELECT EMP_NAME, SALARY, HIRE_DATE, PHONE
FROM employee
WHERE sal_level ='S1';

/* 8번 아직 안배움
SELECT EMP_NAME,SALARY,((SALARY +SALARY*BONUS)*12)-(SALARY*0.07)AS "실수령액",HIRE_DATE
FROM employee
WHERE ((SALARY +SALARY*BONUS)*12)-(SALARY*0.07) >= 50000000;
*/

SELECT *
FROM employee
WHERE SALARY >=4000000 AND JOB_CODE ='J2';

SELECT EMP_NAME, DEPT_CODE, HIRE_DATE
FROM employee
WHERE DEPT_CODE IN ('D9','D5') AND HIRE_DATE < '02/1/1';

SELECT *
FROM employee
WHERE hire_date >= '90/01/01' AND  hire_date <= '01/01/01';

SELECT EMP_NAME
FROM employee
WHERE EMP_NAME LIKE '%연';

SELECT EMP_NAME, PHONE
FROM employee
WHERE NOT PHONE LIKE '010%';

SELECT *
FROM employee
WHERE (DEPT_CODE = 'D6' OR DEPT_CODE = 'D9' )AND email LIKE '____$_%' ESCAPE'$' AND
hire_date >= '90/01/01' AND  hire_date <= '00/12/01' AND SALARY >= 2700000;

SELECT EMP_NAME, SUBSTR(EMP_NO, 1, 2)AS "생년",SUBSTR(EMP_NO, 3, 2)AS "생월",SUBSTR(EMP_NO, 5, 2)AS "생일"
FROM employee;

SELECT EMP_NAME, RPAD(SUBSTR(EMP_NO,1,8),14,'*')
FROM employee;

SELECT EMP_NAME, ABS(TRUNC(HIRE_DATE - SYSDATE)) AS "근무일수1", TRUNC(SYSDATE -HIRE_DATE )AS "근무일수2"
FROM employee;

SELECT *
FROM employee
WHERE MOD(EMP_ID,2) = 1;

SELECT *
FROM employee
WHERE hire_date <= '03/06/26';

SELECT EMP_NAME,TO_CHAR(SALARY,'L999,999,999') 
FROM employee;

SELECT EMP_NAME, DEPT_CODE, SUBSTR(EMP_NO,1,6), MONTHS_BETWEEN(SYSDATE, TO_DATE(EMP_NO, 'YYYYMMDD'))
FROM employee;

